version: '3.7'

services:
  konsume:
    image: bugrakocabay/konsume:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      KONSUME_CONFIG_PATH: /config/config.yaml
    volumes:
      - ./config.yaml:/config/config.yaml

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  kafka:
    image: confluentinc/cp-kafka:latest
    healthcheck:
      test: [ "CMD", "bash", "-c", '/usr/bin/kafka-topics --bootstrap-server localhost:9092 --list' ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
