version: '3.7'

services:
  konsume:
    image: bugrakocabay/konsume:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
    environment:
      KONSUME_CONFIG_PATH: /config/config.yaml
    volumes:
      - ./config.yaml:/config/config.yaml

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"