name: Go

on:
  pull_request:
    branches: [ "dev", "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.4'

      - name: Build
        run: go build -v ./...

      - name: Test with coverage
        run: env "PATH=$PATH" "GOROOT=$GOROOT" go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Codecov
        uses: codecov/codecov-action@v3.1.5
        with:
          files: ./coverage.txt
