name: Go

on:
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'

      - name: Build main application
        run: |
          go build -v -o konsume ./cmd/...
          go build -v -o konsume main.go

      - name: Build plugin
        run: go build -v -buildmode=plugin -o plugin/postgresql/postgres.so ./plugin/postgresql

      - name: Test with coverage
        run: go test ./pkg/... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Codecov
        uses: codecov/codecov-action@v5.0.6
        with:
          files: ./coverage.txt
