name: Release Artifacts

on:
  release:
    types: [published]

jobs:
  build-and-upload-assets:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            artifact_suffix: linux
          - os: macos-latest
            goos: darwin
            artifact_suffix: macos
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'

      - name: Build Application
        run: GOOS=${{ matrix.goos }} go build -o konsume-${{ matrix.goos }}

      - name: Build Plugins
        run: |
          GOOS=${{ matrix.goos }} go build -buildmode=plugin -o plugins/postgres-${{ matrix.goos }}.so ./plugin/postgresql/postgresql.go

      - name: Archive Release Artifacts
        run: tar -czvf konsume-${{ github.event.release.tag_name }}-${{ matrix.goos }}.tar.gz konsume-${{ matrix.goos }} plugins

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./konsume-${{ github.event.release.tag_name }}-${{ matrix.goos }}.tar.gz
          asset_name: konsume-${{ github.event.release.tag_name }}-${{ matrix.goos }}.tar.gz
          asset_content_type: application/gzip
