name: Release Artifacts

on:
  release:
    types: [published]

jobs:
  build-and-upload-assets:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        goos: [linux, darwin]
        include:
          - os: ubuntu-latest
            artifact_suffix: linux
          - os: macos-latest
            artifact_suffix: macos
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'

      - name: Build Application
        run: GOOS=${{ matrix.goos }} go build -o konsume-${{ matrix.artifact_suffix }}

      - name: Build Plugins
        run: |
          GOOS=${{ matrix.goos }} go build -buildmode=plugin -o plugins/postgres-${{ matrix.artifact_suffix }}.so ./plugin/postgresql/postgresql.go

      - name: Archive Release Artifacts
        run: tar -czvf konsume-${{ github.event.release.tag_name }}-${{ matrix.artifact_suffix }}.tar.gz konsume-${{ matrix.artifact_suffix }} plugins

      - name: Upload Release Asset
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./konsume-${{ github.event.release.tag_name }}.tar.gz --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./konsume-${{ github.event.release.tag_name }}-${{ matrix.artifact_suffix }}.tar.gz
          asset_name: konsume-${{ github.event.release.tag_name }}-${{ matrix.artifact_suffix }}.tar.gz
          asset_content_type: application/gzip
          