log: json
debug: true
providers:
  - name: "kafka-queue"
    type: "kafka"
    retry: 5
    kafka-config:
      brokers:
        - "kafka:29092"
      topic: "my-topic"
      group: "group1"

queues:
  - name: "queue-for-kafka"
    provider: "kafka-queue"
    retry:
      enabled: true
      threshold-status: 500
      max-retries: 2
      interval: 5s
      strategy: "fixed"
    routes:
      - name: "ServiceA_Queue1"
        type: "REST"
        method: "POST"
        url: "https://someurl.com"
        headers:
          Content-Type: "application/json"
        timeout: 10s