version: '3.7'

services:
  konsume:
    image: bugrakocabay/konsume:latest
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KONSUME_CONFIG_PATH: /config/config.yaml
    volumes:
      - ./config.yaml:/config/config.yaml

  kafka:
    image: confluentinc/cp-kafka:latest
    healthcheck:
      test: [ "CMD", "bash", "-c", '/usr/bin/kafka-topics --bootstrap-server localhost:9092 --list' ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_EXTERNAL://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000